### ISSUE TITLE
TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by m1rku5** [elpheria/rpc-websockets#110]
Hi,
I'm using rpc-websocket (7.4.12) on my nodejs (4.17.0) react project. But when declare the client I got this error:
TypeError: Super expression must either be null or a function
_inherits
d:/Test/JS/argo/node_modules/@babel/runtime/helpers/inherits.js:5

  2 | 
  3 | function _inherits(subClass, superClass) {
  4 |   if (typeof superClass !== "function" && superClass !== null) {
> 5 |     throw new TypeError("Super expression must either be null or a function");
  6 |   }
  7 | 
  8 |   subClass.prototype = Object.create(superClass && superClass.prototype, {

./node_modules/rpc-websockets/dist/lib/client/websocket.browser.js/WebSocketBrowserImpl<
d:/Test/JS/argo/node_modules/rpc-websockets/dist/lib/client/websocket.browser.js:31

  28 | function _isNativeReflectConstruct() { if (typeof Reflect === "undefined" || !Reflect.construct) return false; if (Reflect.construct.sham) return false; if (typeof Proxy === "function") return true; try { Date.prototype.toString.call(Reflect.construct(Date, [], function () {})); return true; } catch (e) { return false; } }
  29 | 
  30 | var WebSocketBrowserImpl = /*#__PURE__*/function (_EventEmitter) {
> 31 |   (0, _inherits2["default"])(WebSocketBrowserImpl, _EventEmitter);
  32 | 
  33 |   var _super = _createSuper(WebSocketBrowserImpl);
  34 | 

./node_modules/rpc-websockets/dist/lib/client/websocket.browser.js
d:/Test/JS/argo/node_modules/rpc-websockets/dist/lib/client/websocket.browser.js:110

  107 |     }
  108 |   }]);
  109 |   return WebSocketBrowserImpl;
> 110 | }(_eventemitter.EventEmitter);
  111 | /**
  112 |  * factory method for common WebSocket instance
  113 |  * @method
...

My client code is just:
// ms_proxy.js
var WebSocket = require('rpc-websockets').Client

function get_GCS_tables(date, resolve)
{
   let ws = new WebSocket('ws://192.XXX.XXX.XX:3030');

   ws.on('open', () => {
      // call an RPC method with parameters
      ws.call('function', { ref_date: date }).then((result) => {
         resolve(result);

         ws.close();
      })
      .catch((reason) => {
         console.log('error: ', reason);
      });
   });
}

export default get_GCS_tables;

I'm a novice about JS programming, and I've no idea what could be the problem. Can you help me?

Thanks,
   Mirko

**Comment by trasherdk** [comment]
You could start by [reading markdown documentation](https://guides.github.com/features/mastering-markdown/) and format your post properly :smiley:
