### ISSUE TITLE
Subscribe not working. 

### ISSUE THREAD

**Issue by m1rku5** [elpheria/rpc-websockets#112]
Hi, 
I think I don't understand how the events tool works. Now I've a first client that notify an event every second:
```
function send_events()
{
   let ws = new WebSocket(server_addr);

   ws.on('open', () => {
      let name = 'test';

      let i = 0;
      setInterval(() => {
         console.log('i: ', i++);
         ws.notify(name, { i });
      }, 1000);
   });
}
```

And a second one that subscribes the same event:
```
function subscribe_event(resolve)
{
   let ws = new WebSocket(server_addr);
   ws.on('open', () => {
      let name = 'test'
      ws.subscribe(name);
      ws.on(name, () => {
         console.log('new notify');
      });
   });
}
```

But I don't get any notifications, and I don't understand why...

Thanks for your help and time,
    Mirko

**Comment by mkozjak** [comment]
Only server can emit events.

https://github.com/elpheria/rpc-websockets/blob/master/API.md#serveremitname-params

**Comment by m1rku5** [comment]
Ok perfect. Maybe I'm starting to understand. Just another question. Is it possibile to revoke 
an event? if yes how?

Thanks,
   Mirko

**Comment by mkozjak** [comment]
Not directly. You could probably modify the event list object and unset it that way.
