### ISSUE TITLE
Identify disconnecting client.

### ISSUE THREAD

**Issue by m1rku5** [elpheria/rpc-websockets#113]
Hi,
I'd like to identify inside the 'disconnection' server's handler which client is disconnecting. Is there a unique identifier that I can use? And can I use this identifier to understand to which event it was subscribed?

Thanks,
   Mirko

**Comment by mkozjak** [comment]
Yes, @m1rku5, a unique socket identifier should be available through the `_id` key in a callback parameter of `disconnection`.

**Comment by m1rku5** [comment]
Thank @mkozjak. You're right but the 'disconnection' handler is called after that the client has been removed from the list of the events.
