### ISSUE TITLE
Dependency Vulnrabilities

### ISSUE THREAD

**Issue by TheTreeofGrace** [elpheria/rpc-websockets#124]
From an appium package it is giving a critial vulnrability of a package that is used by a package in this package.

│ Critical      │ Prototype pollution in 101                                   │
│ Package       │ 101                                                                     │
│ Patched in    │ No patch available                                           │
│ Dependency of │ appium [dev]                                               │
│ Path          │ appium > appium-flutter-driver > rpc-websockets >  assert-args > 101  │
│ More info     │ https://github.com/advisories/GHSA-cwcx-rxgc-cmw3            │

I think this package no longer uses assert-args. Issue might be to do with package-lock.json file needing to be updates and old node_modules deleted.

**Comment by mkozjak** [comment]
Hello! I think it's up to you to maintain your node_modules directory. Aside from that, latest rpc-websockets version isn't using assert-args nor is it listed in package-lock.json. Can you check what version you are using?

**Comment by mkozjak** [comment]
I'll also do a quick package-lock.json refresh on my end and publish the package, but that shouldn't make any difference to you.

**Comment by TheTreeofGrace** [comment]
Hi thanks,

This can be closed as have itendified it is appium package that needs to update to latest version of appium-flutter-driver where they are using latest version of your module. 

Thanks again :)
