### ISSUE TITLE
Access connected clients

### ISSUE THREAD

**Issue by OhFlohre** [elpheria/rpc-websockets#133]
Is there a way to list all connected clients. Or at least all connected clients for a specific namespace?

**Comment by mkozjak** [comment]
Yes: https://github.com/elpheria/rpc-websockets/blob/trunk/API.md#namespaceconnected---object

**Comment by OhFlohre** [comment]
Well thanks but how do i access namespaces ? It's a private member of the server object

**Comment by mkozjak** [comment]
With this function: https://github.com/elpheria/rpc-websockets/blob/trunk/API.md#serverofname---namespace

**Comment by OhFlohre** [comment]
Oh, thanks alot :D
