### ISSUE TITLE
Is this the proper way to close the socket?

### ISSUE THREAD

**Issue by MassMessage** [elpheria/rpc-websockets#134]
Give a socket server like this:

```
  const wss = new WebSocketServer({
    port: serverPort,
    perMessageDeflate: false
  }, func);
wss.on('connection', ...);
```

what's the proper way to clean up this? i also i'd like to null it when done:

```
    wss .on('close', () => wss = null);
    wss.close();
```
  
Is this the proper way to do this? or I don't need to subscribe to close event for example and just do:

```
    wss.close();
   wss = null;
```

**Comment by mkozjak** [comment]
Yes, all your examples are valid. All good!
