### ISSUE TITLE
When sents message without params it is ignored

### ISSUE THREAD

**Issue by basz** [elpheria/rpc-websockets#153]
Using [moonraker](https://moonraker.readthedocs.io/en/latest/web_api/#klippy-disconnected) as a server, the client is listening for some events without parameters

eg.

`{"jsonrpc": "2.0", "method": "notify_klippy_disconnected"}`

This seems to be ignored and callbacks are never called. I veriefied this by modifiyng `node_modules/rpc-websockets/dist/lib/client.js` in my project.

```
if (!_this4.queue[message.id]) {
          // general JSON RPC 2.0 events
          if (message.method && message.params) {
            // run as microtask so that pending queue messages are resolved first
            return Promise.resolve().then(function () {
              _this4.emit(message.method, message.params);
            });
          }
          return;
        }
```
to
```
if (!_this4.queue[message.id]) {
          // general JSON RPC 2.0 events
          if (message.method) {
            // run as microtask so that pending queue messages are resolved first
            return Promise.resolve().then(function () {
              _this4.emit(message.method, message.params);
            });
          }
          return;
        }
```

When I do that callbacks are being called.

Source would be here

https://github.com/elpheria/rpc-websockets/blob/trunk/src/lib/client.ts#L351

If you agree I can create a PR to fix that

**Comment by mkozjak** [comment]
Yeah, it makes perfect sense. This is actually a part of the previous PR. Feel tree to commit!
