### ISSUE TITLE
Getting error while importing Client

### ISSUE THREAD

**Issue by alexvisai** [elpheria/rpc-websockets#163]
import * as web  from "rpc-websockets";
import { IPC_Events } from "./constants";

let Websocket;
export const socketServer = () => {
  console.log(web)
  Websocket = new web.Client("ws://localhost:7000");
  Websocket.on("open", () => {
    Websocket.subscribe(Object.values(IPC_Events));
  });
  return Websocket;
};

export let socket = socketServer();

This is my code

This is error message I am getting
Can't import the named export 'Client' (imported as 'web') from default-exporting module (only default export is available)

**Comment by mkozjak** [comment]
Which version are you using?

**Comment by alexvisai** [comment]
the error came in 7.11.1(latest)
it works fine in 7.11.0, it shows 7.11.0 as deprecated while I use npm i
npm WARN deprecated rpc-websockets@7.11.0: deprecate 7.11.0

**Comment by mkozjak** [comment]
Hmm, @steveluscher, any ideas?

**Comment by steveluscher** [comment]
Not sure. Can you supply an online repro @alexvisai?

I created one with your code, [here](https://codesandbox.io/p/sandbox/sleepy-jasper-2t8chl?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clx22tn4n00063b6gs6paea8x%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clx22tn4n00023b6gdxuxgl1c%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clx22tn4n00033b6g4t59mdle%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clx22tn4n00053b6ggbqvyts6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clx22tn4n00023b6gdxuxgl1c%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx22tn4n00013b6gbrdwsz47%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.html%2522%257D%255D%252C%2522id%2522%253A%2522clx22tn4n00023b6gdxuxgl1c%2522%252C%2522activeTabId%2522%253A%2522clx22tn4n00013b6gbrdwsz47%2522%257D%252C%2522clx22tn4n00053b6ggbqvyts6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx22tn4n00043b6g0z5k5se5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clx22tn4n00053b6ggbqvyts6%2522%252C%2522activeTabId%2522%253A%2522clx22tn4n00043b6g0z5k5se5%2522%257D%252C%2522clx22tn4n00033b6g4t59mdle%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clx22tn4n00033b6g4t59mdle%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D), and it works.

**Comment by alexvisai** [comment]
@steveluscher check this [code](https://codesandbox.io/p/github/alexvisai/rpc/main?import=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clx242nx300062v6f9zvr83lv%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clx242nx300022v6f4f597r5g%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clx242nx300042v6fkk31anke%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clx242nx300052v6fqjgvgk00%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clx242nx300022v6f4f597r5g%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx242nx200012v6f7xfb8koh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clx242nx300022v6f4f597r5g%2522%252C%2522activeTabId%2522%253A%2522clx242nx200012v6f7xfb8koh%2522%257D%252C%2522clx242nx300052v6fqjgvgk00%2522%253A%257B%2522id%2522%253A%2522clx242nx300052v6fqjgvgk00%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clx243zta00ac2v6fo7hxhe5d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clx243zta00ac2v6fo7hxhe5d%2522%257D%252C%2522clx242nx300042v6fkk31anke%2522%253A%257B%2522id%2522%253A%2522clx242nx300042v6fkk31anke%2522%252C%2522activeTabId%2522%253A%2522clx243u8w00872v6fm7ixd59b%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx242nx300032v6fnvblfnjy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clx242o9o000fdlgnfucy0q72%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clx243u8w00872v6fm7ixd59b%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by steveluscher** [comment]
You are using Create React App, which does not support CommonJS-only packages: https://github.com/facebook/create-react-app/issues/12700

Your best bets are:

* Modify your Create React App Webpack config to understand `.cjs` files ([sandbox](https://codesandbox.io/p/github/alexvisai/rpc/csb-3ccyw7/draft/condescending-waterfall?file=%2Fsrc%2FApp.js%3A4%2C10&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clx242nx300062v6f9zvr83lv%2522%252C%2522sizes%2522%253A%255B62.430939226519335%252C37.569060773480665%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clx242nx300022v6f4f597r5g%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clx242nx300042v6fkk31anke%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clx242nx300052v6fqjgvgk00%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clx242nx300022v6f4f597r5g%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx242nx200012v6f7xfb8koh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clx26idsb00023b6f5s5iedk9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A4%252C%2522startColumn%2522%253A10%252C%2522endLineNumber%2522%253A4%252C%2522endColumn%2522%253A10%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clx242nx300022v6f4f597r5g%2522%252C%2522activeTabId%2522%253A%2522clx26idsb00023b6f5s5iedk9%2522%257D%252C%2522clx242nx300052v6fqjgvgk00%2522%253A%257B%2522id%2522%253A%2522clx242nx300052v6fqjgvgk00%2522%252C%2522activeTabId%2522%253A%2522clx26j59d007j3b6fso1nebl3%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clx26j59d007j3b6fso1nebl3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clx242nx300042v6fkk31anke%2522%253A%257B%2522id%2522%253A%2522clx242nx300042v6fkk31anke%2522%252C%2522activeTabId%2522%253A%2522clx27ocgs00ll3b6f7r7r100x%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clx27ocgs00ll3b6f7r7r100x%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D))
* Ask @mkozjak to convert `rpc-websockets` into a package that exports _both_ ESM and CJS.

**Comment by alexvisai** [comment]
@steveluscher  But it worked well in version 7.11.0

**Comment by steveluscher** [comment]
Indeed! Anyway, now you know how to solve it.

**Comment by mkozjak** [comment]
This should’ve been a major version bump. I’ll decide whether I’ll be reverting these commits and rereleasing it as v8.

**Comment by alexvisai** [comment]
That sounds good, I too recommend releasing it as version 8, thanks for your response @mkozjak @steveluscher.

**Comment by mkozjak** [comment]
I have deprecated all v7 versions starting with v7.11.0.
@alexvisai please install v7.10.0 with `npm i rpc-websockets@7.10.0`.

I have also published v8.0.0 with CommonJS changes.
