### ISSUE TITLE
public connect-function for autoconnect:false

### ISSUE THREAD

**Issue by leokra** [elpheria/rpc-websockets#34]
Hello,

thanks for your work on this Module. I have a question regarding the client options:
You can set autoconnect: false upon intialization of the WebSocket.Client. But where can I can actually call something like connect? In the implementation I only found "_connect", which does not seem to be intended as a public function. 

Is there any reason for _connect being private?

**Comment by mkozjak** [comment]
Hi, @leokra! Thank you for this report. Managed not to see this bug. Fixed in 4.1.3!
