### ISSUE TITLE
how to build it to use in webbrowser?

### ISSUE THREAD

**Issue by yriiarutiunian** [elpheria/rpc-websockets#38]
Hello!
how to build it to use in webbrowser?
Thank you in advance.

**Comment by mkozjak** [comment]
Hello,

Build it with `npm build` and check the `dist` directory for browser files. Also check https://github.com/elpheria/rpc-websockets/tree/master/dist

**Comment by yriiarutiunian** [comment]
I got this after I run build

$ npm run build

> rpc-websockets@4.3.5 build C:\Users\me\Documents\tmp\rpc-websockets
> mkdir -p ./dist && eslint --fix -c ./.eslintrc './src/**/*.js' './test/**/*.js' && babel ./src -d ./dist && browserify -s RPCWebSocket ./dist/index.browser.js > ./dist/index.browser-bundle.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rpc-websockets@4.3.5 build: `mkdir -p ./dist && eslint --fix -c ./.eslintrc './src/**/*.js' './test/**/*.js' && babel ./src -d ./dist && browserify -sRPCWebSocket ./dist/index.browser.js > ./dist/index.browser-bundle.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rpc-websockets@4.3.5 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2019-01-17T19_25_41_449Z-debug.log

**Comment by mkozjak** [comment]
For me it worked correctly:
```bash
> rpc-websockets@4.3.5 build /private/tmp/rpc-websockets
> mkdir -p ./dist && eslint --fix -c ./.eslintrc './src/**/*.js' './test/**/*.js' && babel ./src -d ./dist && browserify -s RPCWebSocket ./dist/index.browser.js > ./dist/index.browser-bundle.js

src/index.browser.js -> dist/index.browser.js
src/index.js -> dist/index.js
src/lib/client/websocket.browser.js -> dist/lib/client/websocket.browser.js
src/lib/client/websocket.js -> dist/lib/client/websocket.js
src/lib/client.js -> dist/lib/client.js
src/lib/server.js -> dist/lib/server.js
src/lib/utils.js -> dist/lib/utils.js
```

Try doing `rm -rf node_modules && npm i` preventively.

**Comment by yriiarutiunian** [comment]
No, it wouldn't work for me.
Maybe there's something I do wrong during the install process.
Here it is:
$ git clone https://github.com/elpheria/rpc-websockets.git
$ cd rpc-websockets
$ npm i
$ npm run build

**Comment by mkozjak** [comment]
Which node and npm versions are you running?

**Comment by yriiarutiunian** [comment]
$ npm -v
6.4.1

$ node -v
v10.15.0

**Comment by yriiarutiunian** [comment]
the last one went wrong.
this is what it says:
$ ./node_modules/.bin/browserify -sRPCWebSocket ./dist/index.browser.js > ./dist/index.browser-bundle.js
Error: --standalone requires an export name argument
    at error (C:\tmp1\rpc-websockets\node_modules\browserify\bin\args.js:110:17)
    at module.exports (C:\tmp1\rpc-websockets\node_modules\browserify\bin\args.js:242:9)
    at Object.<anonymous> (C:\tmp1\rpc-websockets\node_modules\browserify\bin\cmd.js:8:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)

**Comment by mkozjak** [comment]
Can you give me an output of this?
```cat package.json| grep build```

**Comment by yriiarutiunian** [comment]
yes, i can. here it is:

$ cat package.json | grep build
    "build": "mkdir -p ./dist && eslint --fix -c ./.eslintrc './src/**/*.js' './test/**/*.js' && babel ./src -d ./dist && browserify -s RPCWebSocket ./dist/index.browser.js > ./dist/index.browser-bundle.js",
    "pretest": "npm run-script build",

but now it gives NO ERROR after I do the last line right,

**Comment by mkozjak** [comment]
Ok, might be that your package.json is messed up. Look at the comment where you posted the `npm run build` line with an error. You had browserify -sRPCWebSocket in it.

**Comment by yriiarutiunian** [comment]
Ok. Thank you. there's one more star from me, man!
