### ISSUE TITLE
ability to get connection

### ISSUE THREAD

**Issue by zh99998** [elpheria/rpc-websockets#41]
I want to save some per-connection variables. for example:
```
class RPCHandler {
  data;
  setMyData(data){
    this.data = data
  }
  getMyData(){
    return data
  }
}
```

but I can't find anyway to tell apart which connection when my rpc methods was called from.

**Comment by mkozjak** [comment]
Just write to your ws object which was generated via
```js
var WebSocket = require('rpc-websockets').Client
var ws = new WebSocket('ws://localhost:8080')
```
or choose from some js-generated variables on the object.
