### ISSUE TITLE
Server should check socket state before calling 'send' method

### ISSUE THREAD

**Issue by coderNeos** [elpheria/rpc-websockets#44]
https://github.com/elpheria/rpc-websockets/blob/2f0f59e181e4b5338b878848a53198bcb199ee6f/src/lib/server.js#L417

In case if client socket closes the connection - 'send' will cause an unhandled rejection, which in some production environments might lead to application crash!

Mentioned problem is relevant to any other socket.send call.

Steps to reproduce:

1. Call some long running rpc task
2. Close client connection
3. After task has finished - unhandledRejection will be triggered

**Comment by mkozjak** [comment]
Hi, @coderNeos! Thanks for reporting! Care to do a PR?

**Comment by coderNeos** [comment]
Hi, i think i will be able to fix that issue in my free time.

**Comment by mkozjak** [comment]
Thank you so much!

**Comment by lucaswxp** [comment]
Anyone got this?

**Comment by coderNeos** [comment]
> Anyone got this?

Nope, i didn't have any spare time to address this issue

**Comment by mkozjak** [comment]
@lucaswxp: Wanna try providing a PR?

**Comment by mkozjak** [comment]
@coderNeos any updates on this one maybe?

**Comment by mkozjak** [comment]
websockets/ws#1532
