### ISSUE TITLE
Add an event for client disconnect of namespace on server

### ISSUE THREAD

**Issue by altjz** [elpheria/rpc-websockets#46]
Great thanks to this nice library.

I need to do some cleanup job after client disconnect from server. Is it possible to emit an event after client disconnect?
```javascript
server.on('disconnect', (socket, request) => {
  // do something cleanup job
});
```
or
```javascript
namespace.on('disconnect', (socket, request) => {
  // do something cleanup job
});
```

**Comment by mkozjak** [comment]
Hi, @altjz! Thanks!

Please use server's `connection` event to get the socket and set events on it.
https://github.com/elpheria/rpc-websockets/blob/master/API.md#event-connection

For example:
```js
server.on('connection', (socket, request) => {
    socket.on('close', () => {
        // do some cleanup job
    })
})
```
websockets/ws is the backend library underneath rpc-websockets, so this applies:
https://github.com/websockets/ws/blob/master/doc/ws.md#event-close-1

**Comment by altjz** [comment]
thanks @mkozjak for quick response.
I tried this before, but is it possible to do some cleanup job after all sockets disconnect from specific namespace?

```javascript
server.on("connection", (socket, request) => {
    socket.on("close", () =>
    {
        const u = url.parse(request.url, true);
        const ns = u.pathname;
        console.log('client.size: ', server.namespaces[ns].clients.size); // this won't be 0
        if (server.namespaces[ns].clients.size === 0) {
            console.log('clean up');
        }
    })
});
```
