### ISSUE TITLE
`Uncaught TypeError: WebSocketServer is not a constructor` in browser w/ webpack

### ISSUE THREAD

**Issue by EzraWeller** [elpheria/rpc-websockets#62]
We're working on a web app using Mithril.js and webpack. Currently getting this error: `Uncaught TypeError: WebSocketServer is not a constructor` when trying
```
const WebSocketServer = require('rpc-websockets').Server
const server = new WebSocketServer({port, host})
```

Locally, the rpc-websocket object looks like:
`{ Server: [Getter], Client: [Function: Client] }`

In the browser, I get:
`{__esModule: true, Client: ƒ}` (no Server)

**Comment by mkozjak** [comment]
Hi, @EzraWeller, does it work with rpc-websockets version 4.x as expected?

**Comment by EzraWeller** [comment]
Seems to be the same problem using both `^4.6.1` and the latest.

**Comment by EzraWeller** [comment]
So, we didn't solve this exactly, but we think the answer is pretty simple: we were trying to create a websocket server inside the browser, which is why the option wasn't available.

**Comment by mkozjak** [comment]
@EzraWeller: Thanks for the info! Should we update the docs or the api itself to make this more clear? Have any opinions on that?
