### ISSUE TITLE
How does server call client method in version 6.x ?

### ISSUE THREAD

**Issue by namnguyentat** [elpheria/rpc-websockets#65]
Thank you very much for this wonderful library.
I am building an application that need server call client method. 
How can I do that in version 6.x ?

**Comment by mkozjak** [comment]
@namnguyentat - by using the callMethod instead of call: https://github.com/elpheria/rpc-websockets/blob/v6.x/API.md#wscallmethod-params-timeout-ws_options---promise

**Comment by namnguyentat** [comment]
@mkozjak Thanks for your answer.
But I mean form `WebsocketServer`, how can I call client method
## Server side
```
const WebSocketServer = require('rpc-websockets').Server;

// instantiate Server and start listening for requests
const server = new WebSocketServer({
  port: 8082,
  host: '',
});

// register an RPC method
server.register('server_method', function(params) {
  return true;
});
```
## Client side (browser)
```
const wsUri = 'ws://localhost:8082';
this.ws = new WebSocketClient(wsUri);
this.ws.registerMethod('client_method', () => {
  console.log('client_method call');
  return true;
});
this.ws.on('open', () => {
  this.ws.callMethod('server_method', 1);
});
```
How can I call `client_method` from server side ?

**Comment by mkozjak** [comment]
You should be able to get to client's socket through this one:
https://github.com/elpheria/rpc-websockets/blob/v6.x/API.md#namespacegetclients---array

**Comment by namnguyentat** [comment]
@mkozjak Thank you very much
