### ISSUE TITLE
v6.x Uncaught (in promise) TypeError: cb is not a function

### ISSUE THREAD

**Issue by namnguyentat** [elpheria/rpc-websockets#67]
https://github.com/elpheria/rpc-websockets/blob/8c6529d12ae8f5df1e5dfaa019c8537c2d8a9abf/src/lib/JsonRpcSocket/index.ts#L573-L591

`cb` is optional parameter here, but `this._socket.send` require that `cb` is a function
So we should add default `cb` function here or require `cb` parameter

**Comment by mkozjak** [comment]
Thanks, @namnguyentat! Would you care to provide a PR for 6.x?

**Comment by namnguyentat** [comment]
@mkozjak 
I've created PR to fix it https://github.com/elpheria/rpc-websockets/pull/68
Please help me check it
Thank you very much
