### ISSUE TITLE
Socket id as parameter in registered methods

### ISSUE THREAD

**Issue by hugohammarstrom** [elpheria/rpc-websockets#71]
It would be really helpful if the socket id (or maybe the socket object?) could be used in the registered methods.

Currently, I'm using [patch-package](https://www.npmjs.com/package/patch-package) to make the necessary changes to get `socketId` passed as a parameter when the method is called.

```js
rpc.register("sum", (params, socketId) => {
  return params[0] + params[1]
});
```

**Comment by mkozjak** [comment]
@hugohammarstrom - Available in v5.2.1!
