### ISSUE TITLE
Uncaught TypeError: WebSocketServer is not a constructor

### ISSUE THREAD

**Issue by gisorliu** [elpheria/rpc-websockets#75]
I installed 'rpc-websockets',and wrote my source code follow the quick start,bu i get the follow error.
Uncaught TypeError: WebSocketServer is not a constructor...

var WebSocket = require('rpc-websockets').Client
var WebSocketServer = require('rpc-websockets').Server

// Uncaught TypeError: WebSocketServer is not a constructor...
var server = new WebSocketServer({
  port: 8080,
  host: 'localhost'
})
...

**Comment by mkozjak** [comment]
Works for me:
```js
var WebSocket = require('rpc-websockets').Client
var WebSocketServer = require('rpc-websockets').Server

// instantiate Server and start listening for requests
var server = new WebSocketServer({
  port: 8080,
  host: 'localhost'
})

server.register('feedUpdated', function(p, s) {
    console.log('msg rcvd from:', s)
})

server.register('secret', function(p, s) {
    console.log('secret msg rcvd from:', s)
}).protected()

server.setAuth(() => {
    console.log('logged in')
    return true
})

nr = '12345678'

const main = async() => {
    var ws = new WebSocket('ws://localhost:8080?socket_id=' + nr)

    ws.on('open', async function() {
        await ws.notify('feedUpdated')

        await ws.login({'username': 'confi1', 'password':'foobar'})

        try {
            await ws.call('secret')
            console.log('ws ok')
        } catch (err) {
            console.log(err)
        }
    })

    var wsu = new WebSocket('ws://localhost:8080?socket_id=9999')

    wsu.on('open', async function() {
        try {
            await wsu.call('secret')
        } catch (err) {
            console.log('wsu', err)
        }
    })
}

main()
```

**Comment by ajrice6713** [comment]
Hey @mkozjak 

I am also seeing this issue. 

Essentially - we have an SDK (written in TypeScript) that uses `rpc-websockets`, and I am building a webapp (NodeJS) using our SDK. 

When I try and instantiate a new `Client` I am getting the following error 

```
rpc_websockets_1.Client is not a constructor
TypeError: rpc_websockets_1.Client is not a constructor
```

Everything I have researched leads me to believe that this is a webpack issue, but none of the fixes I have tried seem to work. 

Our usage of the library is essentially 

```js
import { Client } from "rpc-websockets";

  connect(authParams: RtcAuthParams, options?: RtcOptions) {
    return new Promise<void>((resolve, reject) => {
      let rtcOptions: RtcOptions = {
        websocketUrl: this.defaultWebsocketUrl,
      };

      if (options) {
        rtcOptions = { ...rtcOptions, ...options };
      }
      const websocketUrl = `${rtcOptions.websocketUrl}?client=node&sdkVersion=${sdkVersion}&uniqueId=${this.uniqueDeviceId}`;
      logger.debug(`Connecting to ${websocketUrl}`);
      const ws = new Client(websocketUrl, {
        autoconnect: true,
        reconnect: true,
        max_reconnects: 0, // Unlimited
      });
      this.ws = ws;

      ws.on("sdpOffer", (event) => {
        this.emit("sdpOffer", event);
      });

    // some other listeners
  }
```

And when I run our application (built using create-react-app), I encounter that error. Running outside of the react app, everything works fine. 

In poking around i noticed that there are browser and non browser exports, and I added 

```js
import * as RPCWebsockets from "rpc-websockets";
console.log("RPC Websockets exports:", RPCWebsockets);
```

which outputs `'/static/media/index.browser.460ca62445b2c7374ff9.cjs'` from the react app - whereas if i run the same outside of react i get an object with the expected exported classes like `Client`, `CommonClient`, etc

Running Node v20.12.0 w/ `webpack@5.97.1`
