### ISSUE TITLE
Race condition in client RPC response queue handling

### ISSUE THREAD

**Issue by jstarry** [elpheria/rpc-websockets#83]
First of all, thanks @mkozjak for maintaining this library!

#### Problem
When a client sends an RPC request, this library adds `[resolve, reject]` Promise callbacks to a queue so that they can be called when the RPC server responds. When the response is received over the websocket, those callbacks are invoked and will be resolved asynchronously. However, websocket messages can be batched and processed synchronously. So, later messages on the socket which are just normal JSON RPC notifications will be emitted synchronously causing them to be handled before the async callback.

Example Flow:
Client and server have pubsub interface.
Client subscribes to event type `mySubscription` and wait for a response from server
Server receives the subscription message and responds to the client that notifications for that subscription will be sent with id = 1.
Server then immediately sends notifications with id = 1.
Client receives subscription response from server and invokes the async queue callback to record that notifications will be received at id =1.
Client receives subscription notifications with id = 1 but has not yet recorded that notifications will be received at id = 1 so it drops the message

**Comment by jstarry** [comment]
@mkozjak can you please re-open this issue? This is not fixed yet in Node.js

The issue is that queue messages are resolved via promises which get placed in the microtask queue but notifications messages are added to the nextTick queue. The intent is that queue messages are processed first, but in reality, the Node.js event loop processes the nextTick queue before the microtask queue [1]

I believe the fix is to use `setImmediate` since it runs immediately after the microtask queue if called within an I/O cycle [2]. But importantly, `setImmediate` is a macro task and will only run after microtasks are finished since Node v11 [3]

[1]: https://stackoverflow.com/a/57325561
[2]: https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/#setimmediate-vs-settimeout
[3]: https://blog.insiderattack.net/new-changes-to-timers-and-microtasks-from-node-v11-0-0-and-above-68d112743eb3

**Comment by mkozjak** [comment]
@jstarry fair enough. can you provide a PR tackling this?

**Comment by jstarry** [comment]
will do!
