### ISSUE TITLE
After calling Client.close, Client.connect won't reconnect

### ISSUE THREAD

**Issue by CriesofCarrots** [elpheria/rpc-websockets#87]
After Client.close is called, Client.socket still exists, but with `readyState = CLOSED`. As a result, a subsequent call to Client.connect hits the following check and returns before the connection is re-established:
https://github.com/elpheria/rpc-websockets/blob/2f6b5faf63a74d10ca82560dd476d68ff6783418/src/lib/client.ts#L107

I'm not certain of the best solution here; perhaps different handling based on socket.readyState. But I'd like to be able to reconnect after close without having to create a new Client.

**Comment by mkozjak** [comment]
@CriesofCarrots - Makes sense! Maybe we should check if the [state](https://github.com/websockets/ws/blob/master/doc/ws.md#class-websocket) is 3 and not return in that case.
Also, I think *connect()* should throw on certain states like 0, 1 and 2 to note the user that the connection process is currently in place.

Care to provide a PR addressing those things? Thanks in advance!

**Comment by mkozjak** [comment]
@CriesofCarrots - would be nice to get some more feedback for you since you're the most relevant person to test this feature if it makes sense.

**Comment by CriesofCarrots** [comment]
@jstarry , thanks very much for taking this over!
