### ISSUE TITLE
Why do you use CircularJSON?

### ISSUE THREAD

**Issue by beautyfree** [elpheria/rpc-websockets#94]
We encountered a bug related to the fact that the user wrote a post where on the last line he wrote `~`

This caused the whole object to get into this property instead of the `~`

So why do you use this package? Why didn't you write about it anywhere? Now we have to use either another library or fork this with changes, and that's after 2 years of using it.

**Comment by mkozjak** [comment]
@beautyfree - Since there's more hate in your post than appreciation for years of work myself and other folk did on this library, your post just earned a report towards github for further inspection. I'm also closing this ticket. Hope you're going to learn something outta this situation. Thank you.

**Comment by mkozjak** [comment]
@beautyfree - Be very aware about forking this library checking the LICENSE file of this project. If you do anything wrong with it - I'll charge you. Thank you.
