### ISSUE TITLE
why do I need python when I install this package?

### ISSUE THREAD

**Issue by nshen** [elpheria/rpc-websockets#99]
![image](https://user-images.githubusercontent.com/181506/110756575-59930280-8285-11eb-9db2-3129bbd590aa.png)

**Comment by mkozjak** [comment]
node-gyp requires it. https://github.com/nodejs/node-gyp#on-unix.

**Comment by nshen** [comment]
I think this is a library on top of websocket , why do we need node-gyp though ?

**Comment by mkozjak** [comment]
Peer dependencies still need to be built.
